apiVersion: v1
kind: Namespace
metadata:
  name: fiapx
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: fiapx
type: Opaque
stringData:
  # ATENÇÃO: substitua por valores reais via CI/CD (ex: Sealed Secrets / Vault)
  connection-string: "Host=postgres-service;Port=5432;Database=fiapx_auth;Username=fiapx;Password=fiapx@2024"
  jwt-secret-key: "fiapx-super-secret-key-at-least-32-chars-long!"
