apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fiapx
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/SEU_ORG/fiapx-auth-service:latest   # substituído pelo CI
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: connection-string
            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: jwt-secret-key
            - name: Jwt__Issuer
              value: "fiapx-auth"
            - name: Jwt__Audience
              value: "fiapx-services"
            - name: Jwt__ExpiresMinutes
              value: "60"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fiapx
spec:
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: fiapx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
